# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientShowcase',
            fields=[
                ('tag_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='officialSite/images')),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('date_created', models.DateField()),
                ('category', models.CharField(choices=[('Companies', 'Companies'), ('Churches', 'Churches'), ('Organizations', 'Organizations'), ('Celebrities', 'Celebrities'), ('Schools', 'Schools'), ('Hospitals', 'Hospitals')], default='', max_length=20)),
                ('comments', models.CharField(max_length=200)),
                ('number_of_views', models.IntegerField(default=0)),
                ('number_of_likes', models.IntegerField(default=0)),
                ('number_of_dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='officialSite/images')),
                ('title', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=200)),
                ('modal_photos', models.ImageField(upload_to='officialSite/images')),
            ],
        ),
    ]
