# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='text',
            field=models.CharField(default='TAG1', max_length=100),
            preserve_default=False,
        ),
    ]
