# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officialSite', '0002_gallery_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='text',
        ),
    ]
