# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialSite', '0004_auto_20170318_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_showcase',
            name='category',
            field=models.CharField(choices=[('Institutions', 'Institutions'), ('Churches', 'Churches'), ('Organizations', 'Organizations'), ('Celebrities', 'Celebrities'), ('Schools', 'Schools'), ('Hospitals', 'Hospitals')], default='', max_length=20),
        ),
    ]
