# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialSite', '0005_auto_20170318_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_showcase',
            name='client_website',
            field=models.URLField(default='www.example.com'),
            preserve_default=False,
        ),
    ]
