# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialSite', '0006_client_showcase_client_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_showcase',
            name='modal_photos',
            field=models.ImageField(default='modal_photos', upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client_showcase',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='modal_photos',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
